// ActionTypes for user authentication 
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const LOGOUT = 'LOGOUT';


// redux/actionTypes.js
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS';
export const FOLLOW_USER_FAILURE = 'FOLLOW_USER_FAILURE';
export const UNFOLLOW_USER_SUCCESS = 'UNFOLLOW_USER_SUCCESS';
export const UNFOLLOW_USER_FAILURE = 'UNFOLLOW_USER_FAILURE';

// tweetActionTypes.js
export const CREATE_TWEET_SUCCESS = 'CREATE_TWEET_SUCCESS';
export const CREATE_TWEET_FAILURE = 'CREATE_TWEET_FAILURE';

export const GET_TWEET_SUCCESS = 'GET_TWEET_SUCCESS';
export const GET_TWEET_FAILURE = 'GET_TWEET_FAILURE';

export const EDIT_TWEET_SUCCESS = 'EDIT_TWEET_SUCCESS';
export const EDIT_TWEET_FAILURE = 'EDIT_TWEET_FAILURE';

export const DELETE_TWEET_SUCCESS = 'DELETE_TWEET_SUCCESS';
export const DELETE_TWEET_FAILURE = 'DELETE_TWEET_FAILURE';

export const GET_ALL_TWEETS_WITH_PROFILES_SUCCESS = 'GET_ALL_TWEETS_WITH_PROFILES_SUCCESS';
export const GET_ALL_TWEETS_WITH_PROFILES_FAILURE = 'GET_ALL_TWEETS_WITH_PROFILES_FAILURE';

export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS'; // New action type for fetching all users
export const GET_ALL_USERS_FAILURE = 'GET_ALL_USERS_FAILURE';
export const GET_TIMELINE_SUCCESS = "GET_TIMELINE_SUCCESS";
export const GET_TIMELINE_FAILURE = "GET_TIMELINE_FAILURE";

export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_FAILURE = "EDIT_PROFILE_FAILURE";
// chatActionTypes.js

export const SEND_MESSAGE = "SEND_MESSAGE";
export const RECEIVE_MESSAGE = "RECEIVE_MESSAGE";

